//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleDesktop2._0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink1 {
            get {
                return ((string)(this["QuickLink1"]));
            }
            set {
                this["QuickLink1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink2 {
            get {
                return ((string)(this["QuickLink2"]));
            }
            set {
                this["QuickLink2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink3 {
            get {
                return ((string)(this["QuickLink3"]));
            }
            set {
                this["QuickLink3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink4 {
            get {
                return ((string)(this["QuickLink4"]));
            }
            set {
                this["QuickLink4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink5 {
            get {
                return ((string)(this["QuickLink5"]));
            }
            set {
                this["QuickLink5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Url...")]
        public string QuickLink6 {
            get {
                return ((string)(this["QuickLink6"]));
            }
            set {
                this["QuickLink6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink1Name {
            get {
                return ((string)(this["QuickLink1Name"]));
            }
            set {
                this["QuickLink1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink2Name {
            get {
                return ((string)(this["QuickLink2Name"]));
            }
            set {
                this["QuickLink2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink3Name {
            get {
                return ((string)(this["QuickLink3Name"]));
            }
            set {
                this["QuickLink3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink4Name {
            get {
                return ((string)(this["QuickLink4Name"]));
            }
            set {
                this["QuickLink4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink5Name {
            get {
                return ((string)(this["QuickLink5Name"]));
            }
            set {
                this["QuickLink5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string QuickLink6Name {
            get {
                return ((string)(this["QuickLink6Name"]));
            }
            set {
                this["QuickLink6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp1Name {
            get {
                return ((string)(this["QuickApp1Name"]));
            }
            set {
                this["QuickApp1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp2Name {
            get {
                return ((string)(this["QuickApp2Name"]));
            }
            set {
                this["QuickApp2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickApp3Name {
            get {
                return ((string)(this["QuickApp3Name"]));
            }
            set {
                this["QuickApp3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp1 {
            get {
                return ((string)(this["QuickApp1"]));
            }
            set {
                this["QuickApp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp2 {
            get {
                return ((string)(this["QuickApp2"]));
            }
            set {
                this["QuickApp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter Path...")]
        public string QuickApp3 {
            get {
                return ((string)(this["QuickApp3"]));
            }
            set {
                this["QuickApp3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyCTEZNcC9Le1GPrU7qdFruVyo52NzFUQtY")]
        public string YouTubeApiKey {
            get {
                return ((string)(this["YouTubeApiKey"]));
            }
            set {
                this["YouTubeApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBr5FK93FZvdZtsEMV8uQX61k-4JTM--lA")]
        public string YouTubeApiKey2 {
            get {
                return ((string)(this["YouTubeApiKey2"]));
            }
            set {
                this["YouTubeApiKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAZU3JNyiv-JiMZg5h7YIP3fUWZr0IwDM4")]
        public string YouTubeApiKey3 {
            get {
                return ((string)(this["YouTubeApiKey3"]));
            }
            set {
                this["YouTubeApiKey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAS-EGRuAajTCrjOD5k7pJhPvFc1dWH_1U")]
        public string YouTubeApiKey4 {
            get {
                return ((string)(this["YouTubeApiKey4"]));
            }
            set {
                this["YouTubeApiKey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBWpZx2jJl_gKneHMVKsKGIJvKO1Yjapp4")]
        public string YouTubeApiKey5 {
            get {
                return ((string)(this["YouTubeApiKey5"]));
            }
            set {
                this["YouTubeApiKey5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAV_MAEY-AOpvWs6KrgigAUcqqxYInaTqo")]
        public string YouTubeApiKey6 {
            get {
                return ((string)(this["YouTubeApiKey6"]));
            }
            set {
                this["YouTubeApiKey6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAf4B4EJLnL1FWi9np3Xh6zfW2BaYBDXGM")]
        public string YouTubeApiKey7 {
            get {
                return ((string)(this["YouTubeApiKey7"]));
            }
            set {
                this["YouTubeApiKey7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAqUR0P7szTnmyv6AZb38JuuNycJVo12WU")]
        public string YouTubeApiKey8 {
            get {
                return ((string)(this["YouTubeApiKey8"]));
            }
            set {
                this["YouTubeApiKey8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAaih4FrKO1MLdepApopbgjTNVdFHutenc")]
        public string YouTubeApiKey9 {
            get {
                return ((string)(this["YouTubeApiKey9"]));
            }
            set {
                this["YouTubeApiKey9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBqTcC84xgHfn6uk3H0mNHlfesYNVtZaA4")]
        public string YouTubeApiKey10 {
            get {
                return ((string)(this["YouTubeApiKey10"]));
            }
            set {
                this["YouTubeApiKey10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyAOzDby3TIhafOjNAlJndXIfRRDI6Tmyr4")]
        public string YouTubeApiKey11 {
            get {
                return ((string)(this["YouTubeApiKey11"]));
            }
            set {
                this["YouTubeApiKey11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Void")]
        public string OpenAiToken {
            get {
                return ((string)(this["OpenAiToken"]));
            }
            set {
                this["OpenAiToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TokenSaved {
            get {
                return ((bool)(this["TokenSaved"]));
            }
            set {
                this["TokenSaved"] = value;
            }
        }
    }
}
